# To execute this docker compose yml file use `docker compose -f docker-compose-v2.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker compose -f docker-compose-v2.yml down`
version: '2'
services:
  chrome:
    image: selenium/node-chrome:4.29.0-20250303
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
    ports:
      - "6900:5900"

  edge:
    image: selenium/node-edge:4.29.0-20250303
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
    ports:
      - "6901:5900"

  firefox:
    image: selenium/node-firefox:4.29.0-20250303
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
    ports:
      - "6902:5900"

  selenium-hub:
    image: selenium/hub:4.29.0-20250303
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
